Repository Eduhub-Community/Eduhub-Community.github.io, pull requests merged in 2022-10, with the labels that each got.

#57 Contributors added
  README.md
Labels: Hacktoberfest22, hacktoberfest-accepted, hacktoberfest

#58 Contact form is working with javaScript
  assets/css/style.css
  assets/js/main.js
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#91 Create home-2.html
  home-2.html
Labels: Hacktoberfest22, hacktoberfest-accepted, hacktoberfest

#92 bug
  index.html
Labels: Hacktoberfest22, hacktoberfest-accepted, hacktoberfest

#93 fixing event card bug
  eventPage.html
Labels: Hacktoberfest22, hacktoberfest-accepted, hacktoberfest

#94 after switch to dark mode, the invisible texts now showing.
  assets/css/style.css
Labels: Hacktoberfest22

#124 Create javascript
  blog/javascript
Labels: Hacktoberfest22, hacktoberfest-accepted

#119 fix of text not showing proper in normal mode(white)
  assets/css/dark-mode-style.css
Labels: Hacktoberfest22, hacktoberfest-accepted
