Repository Eduhub-Community/Eduhub-Community.github.io, pull requests merged in 2023-06, with the labels that each got.

#367 Added Google Maps in contact section
  index.html
  style.css
Labels: gssoc23, level1

#406 Justify Paragraphs
  index.html
  style.css
Labels: good first issue, gssoc23

#458 Fixed readme: broken discord link
  README.md
Labels: gssoc23-accepted, level1
